// Code generated by mockery v1.0.0. DO NOT EDIT.

package model

import context "context"
import mock "github.com/stretchr/testify/mock"

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: ctx, email, msg
func (_m *MockService) SendEmail(ctx context.Context, email string, msg string) error {
	ret := _m.Called(ctx, email, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
